=== kiltz/jee/exkurs-05-WS-Grundlagen/schema/weine.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Friedrich Kiltz (Kiltz-Webanwendungen) -->
<!-- mit Namespace  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  = Namespache xs, w3org-Konform 
    targetNamespace="http://www.kiltz.de"               = definiert durch www.kiltz.de 
    xmlns="http://www.kiltz.de"                         = defaultNamespace ist www.kiltz.de 
    elementFormDefault="qualified">                     = jedes Element benötigt einen Namespace 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.kiltz.de"   
    xmlns="http://www.kiltz.de"             
    elementFormDefault="qualified">
-->
<!-- ohne NameSpace Location -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation xml:lang="de">Die Beschreibung einer Flasche Wein</xs:documentation>
	</xs:annotation>
	<xs:element name="WeinListe">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Wein" maxOccurs="unbounded"/>
				<!-- bestimmt die Reihenfolge -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Wein">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Jahrgang"/>
				<xs:element name="Rebsorte">
					<xs:complexType>
						<xs:attribute name="Art" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Geschmack" type="GeschmackTyp"/>
				<xs:element name="Lage" type="xs:string"/>
				<xs:element name="Qualifikation" type="xs:string" minOccurs="0"/>
				<xs:element name="Zahlen" type="ZahlenTyp"/>
				<!-- bestimmt die Reihenfolge -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ZahlenTyp">
		<xs:sequence>
			<xs:element name="Preis" type="PreisTyp"/>
			<xs:element name="Menge" type="xs:string"/>
			<xs:element name="WeinNummer" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Jahrgang">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1900"/>
				<xs:maxInclusive value="2004"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="GeschmackTyp">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Richtung" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PreisTyp">
		<xs:simpleContent>
			<xs:extension base="xs:float">
				<xs:attribute name="Waehrung" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== kiltz/jee/exkurs-05-WS-Grundlagen/schema/weine.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Das Wurzelelement -->
<!-- mit NameSpace Location 
<WeinListe xmlns="http://www.kiltz.de"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.kiltz.de weine.xsd">
-->
<!-- ohne NameSpace Location -->
<WeinListe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="weine.xsd">
	<Wein>
		<Jahrgang>2004</Jahrgang>
		<Rebsorte Art="Weisser Burgunder"/>
		<Geschmack Richtung="trocken">
           Wir lassen diesen Wein 6 Monate in frischen handgearbeiteten 
           Eichenholz Fässern reifen. Dieses alte Verfahren behalten wir nur 
           ausgesuchten und besten Trauben, vor. Ein feines Bouquet und ein 
           Traum aus Leichtigkeit und fruchtigen Aromen ist das Ergebnis. 
        </Geschmack>
		<Lage>
			Kreuznacher Römerberg
		</Lage>
		<Zahlen>
			<Preis>5.01</Preis>
			<Menge>
				0,5 l
			</Menge>
			<WeinNummer>
				01
			</WeinNummer>
		</Zahlen>
	</Wein>
	<!-- Der nächste Datensatz -->
	<Wein>
		<Jahrgang>2000</Jahrgang>
		<Rebsorte Art="Riesling"/>
		<Geschmack Richtung="trocken">
           Ein klassischer Riesling, sonnenverwöhnt und fruchtig. Er macht 
           sowohl als Begleiter zu Käse und Fisch aber auch als Entree in 
           einen stimmungsvollen Abend besonders viel Freude. 
        </Geschmack>
		<Lage>
			Kirschroter Bobbes
		</Lage>
		<Zahlen>
			<Preis>3.68</Preis>
			<Menge>
				0,75 l
			</Menge>
			<WeinNummer>
				02
			</WeinNummer>
		</Zahlen>
	</Wein>
	<!-- Der nächste Datensatz -->
	<Wein>
		<Jahrgang>1998</Jahrgang>
		<Rebsorte Art="Riseling Eiswein"/>
		<Geschmack Richtung="trocken">
           Lassen Sie sich verführen durch sein fruchtiges Bouquet und seine 
           goldgelbe Farbe. Das Beste was der Sommer zu bieten hat wird in 
           diesem Wein lebendig. Lassen Sie Ihre Sinne von diesem 
           außerordentlichen Wein umschmeicheln und erleben Sie ein 
           Geschmackserlebnis der besonderen Art. 
        </Geschmack>
		<Lage>
			Gutenberger Hinkelstein
		</Lage>
		<Zahlen>
			<Preis>18.41</Preis>
			<Menge>
				0,375 l
			</Menge>
			<WeinNummer>
				03
			</WeinNummer>
		</Zahlen>
	</Wein>
	<!-- Ende des Wurzelelementes -->
</WeinListe>
